import { Canvas } from '@react-three/fiber'
import { Suspense, useState } from 'react'
import Starfield from './components/Starfield'
import ParticleRing from './components/ParticleRing'
import StartButton from './components/StartButton'